### ISSUE TITLE
Feature request: Print data string when clicking in plotQPlane

### ISSUE THREAD

**Issue by SJanas** [Jakob-Lass/MJOLNIR#32]
Ability to print the [h k l I E Cts Norm Mon Normcount] string when clicking on point in Plotting a Q plane for constant energy tutorial style, i.e. as part of plotQPlane.

Very nice that this works in plotCutQELine.

**Comment by Jakob-Lass** [comment]
Included in the a8158b0b69a9fd8f36b0e1295a64090a4479c836 commit for plots in 2D both reciprocal lattice units and normal plots. Nearest point is calculated from the centers of pixels and might thus not be perfect if one clicks exactly at a corner or edge. 
Prints:
H K L (or qx,qy), Intensity, cts, normalization, monitor, normalization count.
