### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by henrikjacobsenfys** [Jakob-Lass/MJOLNIR#38]
I get the following warning when I try and plot data:

c:\program files\python37\lib\site-packages\MJOLNIR\Data\DataFile.py:54: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  with hdf.File(fileLocation) as f:

**Comment by Jakob-Lass** [comment]
Thanks for pointing this out!

This warning originates as a future warning from the h5py library, where the default mode will change. It has been incorporated into the update 3b706be2862300cd86e6a1d2f73a4d3e83a35e40
