### ISSUE TITLE
Bug when clicking on points using View3d

### ISSUE THREAD

**Issue by henrikjacobsenfys** [Jakob-Lass/MJOLNIR#43]
The position displayed when hovering and/or clicking on points is wrong, see attached example. The x axis is 110, the y axis is E, but it shows h,k,l. Moving the mouse to the right increments l. 

import IPython
shell = IPython.get_ipython()
shell.enable_matplotlib(gui='qt')
from MJOLNIR.Data import DataSet
from MJOLNIR import _tools # Usefull tools useful across MJOLNIR
import numpy as np
import matplotlib.pyplot as plt
plt.ion()
numbers = '178-190' # String of data numbers
fileList = _tools.fileListGenerator(numbers,'rawdata/',2018) # Create file list from 2018 in specified folder
# Create the data set
ds = DataSet.DataSet(fileList)
ds.convertDataFile(saveFile=False)
Viewer = ds.View3D(1.0,0.03,0.05)
Viewer.setProjection(0)
Viewer.caxis=(0,5e-8)

**Comment by Jakob-Lass** [comment]
Hi Henrik

This is a genuine bug that has happend in the view3D object, and is not dependent on the specified data files or code, but it happens also for me in a python terminal with different data files. I am currently unaware of the reason for this but will look into it shortly.

**Comment by Jakob-Lass** [comment]
Error was found and corrected 8fb6e1367aacb5b3d6ec98980449e9234e4c4ec1.
It originated from a redefinition of the ax.format_coord functions for the three different axis used in the Viewer3D object.
