### ISSUE TITLE
Issues using MJOLNIRHistory on Windows

### ISSUE THREAD

**Issue by henrikjacobsenfys** [Jakob-Lass/MJOLNIR#50]
This might be Windows-specific, and it might also be me-specific. I've installed MJOLNIR through pip. I Use Windows 10. MJOLNIR was installed using an admin account that I otherwise do not use.

When trying to use MJOLNIRHistory in Spyder, I get the following error:

NameError: name 'MJOLNIRHistory' is not defined.

Upon searching for MJOLNIRHistory I find it in C:\Program Files\Python37\Scripts, along with 3 other files:
MJOLNIRHistory
MJOLNIRConvert
MJOLNIRCalibrationInspector
MJOLNIR3DView

These files do not have any extension. I cannot easily give them a .py extension, as this requires admin access.

I have opened MJOLNIRHistory and saved a copy as MJOLNIRHistory.py in my current working directory. I then run it in Spyder. It gives me a pop up (although it pops up in the background, so I didn't notice it), and i can then select a .hdf file. I then get the following error:

runfile('C:/Users/jacobsen_h/Dropbox/MJOLINRfun/MJOLNIRHistory.py', wdir='C:/Users/jacobsen_h/Dropbox/MJOLINRfun')
Traceback (most recent call last):

  File "C:\Users\jacobsen_h\Dropbox\MJOLINRfun\MJOLNIRHistory.py", line 35, in <module>
    _tools.updateSetting(settingsName,files)

  File "c:\program files\python37\lib\site-packages\MJOLNIR\CommandLineScripts\_tools.py", line 38, in updateSetting
    with open(settingsFile,"wb") as pickle_out:

PermissionError: [Errno 13] Permission denied: 'c:\\program files\\python37\\lib\\site-packages\\MJOLNIR\\CommandLineScripts\\.settings'

**Comment by Jakob-Lass** [comment]
Does this error persist after the updated contained in a625329c9798ccca4503fec5676d4c0035cae171 i.e. the new version 1.1.6?

**Comment by henrikjacobsenfys** [comment]
Yes and no. MJOLNIRHistory now runs from the terminal, but I still get the permission errors

**Comment by Jakob-Lass** [comment]
Writing folder changed to home folder as of 7452d533ddc9a7214c7c1ee912d7bd16cb45688d to ensure writing permissions.
