### ISSUE TITLE
Feature request: 1D line cuts i data

### ISSUE THREAD

**Issue by SJanas** [Jakob-Lass/MJOLNIR#8]
Being able to make 1D line cuts on data would be a great addition. Foremost, my request is on making line cuts within a specific energy plane with arbitrary q-points as start and end points.

-Sofie

**Comment by Jakob-Lass** [comment]
This feature has been introduced in the e28f915a7b086c73f0ac4ddad7530958bc0a0023 of the 1.0.0 branch. This includes:
- Cutting in 1D for constant energy
- Cutting in 2D by consecutive 1D constant energy cuts
- Plotting the 1D cuts with adapted tick labels and tool-hint values
- Plotting the 2D cuts with adapted tick labels and tool-hint values
