### ISSUE TITLE
Feature request: energy planes normalization

### ISSUE THREAD

**Issue by SJanas** [Jakob-Lass/MJOLNIR#9]
The intensity in each energy plane should rightly be normalised by a factor of 1/(k_F^3*cot(theta)) (see e.g. Neutron Scattering with a Triple-Axis Spectrometer, Shirane et al). 
Note: if theta is not in the data file, it can be calculated via q=2*k_F*sin(theta), and PG has q=1.87325 A^-1

-Sofie

**Comment by Jakob-Lass** [comment]
I am currently unsure whether or not the k_f^3 normalization is already taken care of by the use of Vanadium normalization scans. And further, the theta of your formula, does it referer to A3 or A5? (I have the Shirane book so a formula in there is also just fine)

**Comment by SJanas** [comment]
Hmm, Im not so familiar with the vanadium scans, so I cant be sure... the theta is theta_analyzer (which is why its related to the PG crystal), which must be A6/2. Its in Shirane eq. 5.2 and in section 5.1.1

**Comment by Jakob-Lass** [comment]
After a discussion with Christof, it was agreed that the normalization factor from the measurement volume in reciprocal space is taken into account by the use of the Vanadium normalization and an extra factor is not neede.
